# Generated by Django 4.0.5 on 2022-07-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0003_company_family_console'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AddField(
            model_name='console',
            name='twitch_id',
            field=models.IntegerField(default=None, null=True, verbose_name='Twitch ID'),
        ),
    ]
