# Generated by Django 4.0.5 on 2022-07-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0004_alter_company_options_alter_family_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('release', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('storyline', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rating_count', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('console', models.ManyToManyField(to='nerdvanapp.console')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
