# Generated by Django 4.0.5 on 2022-07-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0006_gamecompany_alter_user_options_games_game_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
