# Generated by Django 4.0.5 on 2022-07-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0009_add_games_via_json_pt2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
