# Generated by Django 4.0.5 on 2022-11-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0016_user_email_validated_user_validated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validated_on',
            field=models.DateTimeField(),
        ),
    ]
