# Generated by Django 4.0.5 on 2022-11-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0017_alter_user_validated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
