# Generated by Django 4.0.5 on 2022-12-01 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0018_user_password_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_on', models.DateTimeField()),
                ('resolved_on', models.DateTimeField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('price_resolved', models.DecimalField(decimal_places=2, max_digits=8)),
                ('link_resolved', models.CharField(max_length=256)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdvanapp.games')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price alert',
                'verbose_name_plural': 'Price alerts',
            },
        ),
    ]
