# Generated by Django 4.1.3 on 2023-01-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0020_alter_pricealert_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='console',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
