# Generated by Django 4.1.3 on 2023-03-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0021_pricealert_console'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
