# Generated by Django 4.1.3 on 2023-06-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0022_alter_user_validated_on'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='games',
            index=models.Index(fields=['name'], name='nerdvanapp__name_20df41_idx'),
        ),
    ]
