# Generated by Django 4.1.3 on 2023-09-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0025_add_games_via_json_pt8'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_cover_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
