# Generated by Django 4.1.3 on 2023-11-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdvanapp', '0027_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='top_game',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
