version: "3"
services:
  api:
      container_name: api
      network_mode: local-net
      build:
        context: .
        dockerfile: DockerFiles/Dockerfile-API
      volumes:
        - .:/app/
      env_file:
        - /nerdvana/.env
      ports:
        - '8000:8000'
  broker:
      container_name: broker
      network_mode: local-net
      hostname: rabbitmqhost
      ports:
          - '15672:15672'
          - '5672:5672'
      image: 'rabbitmq:3-management'

  celery-email:
    container_name: celery-email
    network_mode: local-net
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile-Celery
    volumes:
      - .:/app
    command: celery -A nerdvana worker -Q email_sending -l info -P gevent
    environment:
      DEBUG: "True"
    env_file:
      - /nerdvana/.env
    depends_on:
      - broker

  celery-pricing:
    container_name: celery-pricing
    network_mode: local-net
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile-Celery
    volumes:
      - .:/app
    command: celery -A nerdvana worker -Q game_pricing -l info -P gevent
    environment:
      DEBUG: "True"
    env_file:
      - /nerdvana/.env
    depends_on:
      - broker

  celeryscheduler:
    container_name: celeryscheduler
    network_mode: local-net
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile-Celery
    volumes:
      - .:/app
    command: celery -A nerdvana beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      DEBUG: "True"
    env_file:
      - /nerdvana/.env
    depends_on:
      - celery-pricing

volumes:
  rabbitmq_data: