version: "3"
services:
  api:
      network_mode: local-net
      build:
        context: .
        dockerfile: ./Dockerfile
      command:
        - python ./NerdvanaAPI/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/app
      ports:
        - '8000:8000'
  broker:
      container_name: broker
      network_mode: local-net
      hostname: rabbitmqhost
      ports:
          - '15672:15672'
          - '5672:5672'
      image: 'rabbitmq:3-management'

  celery:
    container_name: celery
    network_mode: local-net
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    command: celery -A nerdvana worker -l info -P gevent
    environment:
      DEBUG: "True"
    depends_on:
      - broker

  celeryscheduler:
    container_name: celeryscheduler
    network_mode: local-net
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    command: celery -A nerdvana beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      DEBUG: "True"
    depends_on:
      - celery

volumes:
  rabbitmq_data: