# Generated by Django 4.0.5 on 2022-10-11 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('Password Recovery', 'Password Recovery'), ('Email Validation', 'Email Validation'), ('Game Price Alert', 'Game Price Alert')], max_length=20, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sent Notification',
                'verbose_name_plural': 'Sent Notifications',
            },
        ),
    ]
