# Generated by Django 4.0.5 on 2022-10-18 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateEmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=6)),
                ('creation_date', models.DateTimeField()),
                ('reason', models.CharField(choices=[('Password Recovery', 'Password Recovery'), ('Email Validation', 'Email Validation'), ('Game Price Alert', 'Game Price Alert')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validate E-mail Code',
                'verbose_name_plural': 'Validate E-mail Codes',
            },
        ),
        migrations.CreateModel(
            name='PasswordRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=6)),
                ('creation_date', models.DateTimeField()),
                ('reason', models.CharField(choices=[('Password Recovery', 'Password Recovery'), ('Email Validation', 'Email Validation'), ('Game Price Alert', 'Game Price Alert')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Recovery Code',
                'verbose_name_plural': 'Password Recovery Codes',
            },
        ),
    ]
