# Generated by Django 4.0.5 on 2022-10-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_passwordrecoverycode_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrecoverycode',
            name='validated',
            field=models.BooleanField(default=False, null=True, verbose_name='Code was validated?'),
        ),
        migrations.AddField(
            model_name='validateemailcode',
            name='validated',
            field=models.BooleanField(default=False, null=True, verbose_name='Code was validated?'),
        ),
    ]
