from .user import *
from .login import *
from .logout import *
from .register import *
from .games import *
from .recommender import *
from .gamepricing import *
from .utils.custom_basic_views import *
from .email_validation import *
from .password_recovery import *
from .price_alert import *
